# Generated by Django 5.1.15 on 2026-07-16 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Calisan eklenirken uretilen otomatik sifre (ad + 123) tahmin edilebilir oldugundan, hesap sahibi kendi sifresini belirleyene kadar bu bayrak acik kalir ve diger sayfalara erisim engellenir.', verbose_name='Sifre Degistirmeli'),
        ),
    ]
