# Generated by Django 5.1.15 on 2026-07-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheets_url', models.CharField(blank=True, max_length=500, verbose_name="Google Sheets URL'si")),
                ('service_account_json', models.TextField(blank=True, help_text="Google Cloud Console'dan indirilen service account anahtar dosyasının tüm içeriği.", verbose_name='Servis Hesabı JSON İçeriği')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sheets Ayarı',
                'verbose_name_plural': 'Sheets Ayarları',
            },
        ),
    ]
