# Generated by Django 5.1.15 on 2026-08-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordBotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_token', models.CharField(blank=True, max_length=200, verbose_name='Discord Bot Token')),
                ('spreadsheet_id', models.CharField(blank=True, max_length=200, verbose_name="Google Sheets Belge ID'si")),
                ('worksheet_name', models.CharField(blank=True, default='Sales Pipeline', max_length=200, verbose_name='Sekme Adı')),
                ('service_account_json', models.TextField(blank=True, help_text="Google Cloud Console'dan indirilen service account anahtar dosyasının tüm içeriği.", verbose_name='Servis Hesabı JSON İçeriği (credentials.json)')),
                ('poll_minutes', models.PositiveIntegerField(default=30, verbose_name='Kontrol Sıklığı (dakika)')),
                ('stale_days', models.PositiveIntegerField(default=7, verbose_name='Eskime Eşiği (gün)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Discord Bot Ayarı',
                'verbose_name_plural': 'Discord Bot Ayarları',
            },
        ),
    ]
