# Generated by Django 5.1.15 on 2026-08-03 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discordbot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discordbotsettings',
            name='spreadsheet_id',
        ),
        migrations.RemoveField(
            model_name='discordbotsettings',
            name='worksheet_name',
        ),
    ]
