# Generated by Django 5.1.15 on 2026-07-14 11:44

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Marka Adi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='brands/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Marka',
                'verbose_name_plural': 'Markalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Departman Adi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
            ],
            options={
                'verbose_name': 'Departman',
                'verbose_name_plural': 'Departmanlar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Kategori Adi')),
                ('icon', models.CharField(default='bi-box-seam', help_text='Bootstrap Icons sinif adi, orn: bi-laptop', max_length=50, verbose_name='Ikon')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
            ],
            options={
                'verbose_name': 'Cihaz Kategorisi',
                'verbose_name_plural': 'Cihaz Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('model_name', models.CharField(max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seri Numarasi')),
                ('inventory_number', models.CharField(max_length=50, unique=True, verbose_name='Envanter Numarasi')),
                ('purchase_date', models.DateField(verbose_name='Satin Alma Tarihi')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Satin Alma Fiyati')),
                ('warranty_end_date', models.DateField(blank=True, null=True, verbose_name='Garanti Bitis Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='devices/%Y/%m/', verbose_name='Cihaz Fotografi')),
                ('status', models.CharField(choices=[('available', 'Bosta'), ('assigned', 'Zimmetli'), ('maintenance', 'Bakimda'), ('lost', 'Kayip'), ('broken', 'Arizali'), ('retired', 'Hizmet Disi')], default='available', max_length=20, verbose_name='Durum')),
                ('invoice_file', models.FileField(blank=True, null=True, upload_to='devices/invoices/%Y/%m/', verbose_name='Fatura Belgesi')),
                ('warranty_document', models.FileField(blank=True, null=True, upload_to='devices/warranty/%Y/%m/', verbose_name='Garanti Belgesi')),
                ('qr_code', models.ImageField(blank=True, editable=False, null=True, upload_to='devices/qr/%Y/%m/', verbose_name='QR Kod')),
                ('barcode', models.ImageField(blank=True, editable=False, null=True, upload_to='devices/barcode/%Y/%m/', verbose_name='Barkod')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.brand', verbose_name='Marka')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='inventory.devicecategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Cihaz',
                'verbose_name_plural': 'Cihazlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('first_name', models.CharField(max_length=50, verbose_name='Ad')),
                ('last_name', models.CharField(max_length=50, verbose_name='Soyad')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-posta')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Pozisyon')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='employees/%Y/%m/', verbose_name='Profil Fotografi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif Calisan')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='inventory.department', verbose_name='Departman')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici Hesabi')),
            ],
            options={
                'verbose_name': 'Calisan',
                'verbose_name_plural': 'Calisanlar',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='inventory.employee', verbose_name='Departman Yoneticisi'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('assigned_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Teslim Tarihi')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='Beklenen Iade Tarihi')),
                ('returned_date', models.DateField(blank=True, null=True, verbose_name='Gercek Iade Tarihi')),
                ('notes', models.TextField(blank=True, verbose_name='Teslim Notu')),
                ('return_notes', models.TextField(blank=True, verbose_name='Iade Notu')),
                ('returned', models.BooleanField(default=False, verbose_name='Iade Edildi mi')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_created', to=settings.AUTH_USER_MODEL, verbose_name='Teslim Eden')),
                ('returned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments_returned', to=settings.AUTH_USER_MODEL, verbose_name='Iadeyi Alan')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.device', verbose_name='Cihaz')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='inventory.employee', verbose_name='Calisan')),
            ],
            options={
                'verbose_name': 'Zimmet',
                'verbose_name_plural': 'Zimmetler',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Guncellenme Tarihi')),
                ('company', models.CharField(max_length=150, verbose_name='Bakim Firmasi')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Maliyet')),
                ('start_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Baslangic Tarihi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Bitis Tarihi')),
                ('description', models.TextField(blank=True, verbose_name='Aciklama')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('in_progress', 'Devam Ediyor'), ('completed', 'Tamamlandi'), ('cancelled', 'Iptal Edildi')], default='pending', max_length=20, verbose_name='Bakim Durumu')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='inventory.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Bakim Kaydi',
                'verbose_name_plural': 'Bakim Kayitlari',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Baslik')),
                ('message', models.CharField(max_length=255, verbose_name='Mesaj')),
                ('link', models.CharField(blank=True, max_length=255, verbose_name='Baglanti')),
                ('is_read', models.BooleanField(default=False, verbose_name='Okundu mu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Olusturulma Tarihi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Bildirim',
                'verbose_name_plural': 'Bildirimler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Olusturma'), ('update', 'Guncelleme'), ('delete', 'Silme'), ('login', 'Giris'), ('logout', 'Cikis'), ('assign', 'Zimmetleme'), ('return', 'Iade'), ('maintenance', 'Bakim'), ('other', 'Diger')], max_length=20, verbose_name='Islem Tipi')),
                ('description', models.CharField(max_length=255, verbose_name='Aciklama')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Adresi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Tarih')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanici')),
            ],
            options={
                'verbose_name': 'Sistem Hareketi',
                'verbose_name_plural': 'Sistem Hareketleri',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='inventory_a_created_fcdbcb_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='inventory_d_status_458222_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='inventory_d_serial__ed8962_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['inventory_number'], name='inventory_d_invento_8051a7_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(condition=models.Q(('returned', False)), fields=('device',), name='unique_active_assignment_per_device'),
        ),
    ]
