# Generated by Django 5.1.15 on 2026-07-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HrImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headers', models.JSONField(blank=True, default=list)),
                ('employees', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrSentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HrSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email', models.CharField(blank=True, max_length=255)),
                ('recipient_emails', models.JSONField(blank=True, default=list)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.IntegerField(blank=True, null=True)),
                ('smtp_user', models.CharField(blank=True, max_length=255)),
                ('smtp_pass', models.CharField(blank=True, max_length=255)),
                ('smtp_secure', models.BooleanField(default=False)),
                ('mail_from', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
