# Generated by Django 5.1.15 on 2026-07-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HrEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='İşe Giriş Tarihi')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi')),
                ('allergy_info', models.CharField(blank=True, max_length=255, verbose_name='Alerji Bilgisi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.DeleteModel(
            name='HrImport',
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son Bildirim Tarihi'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='notification_email',
            field=models.CharField(blank=True, max_length=255, verbose_name='Bildirim Gönderilecek E-posta'),
        ),
        migrations.AddField(
            model_name='hrsettings',
            name='notifications_enabled',
            field=models.BooleanField(default=True, verbose_name='Bildirim Açık/Kapalı'),
        ),
    ]
