# Generated by Django 5.1.15 on 2026-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_hremployee_delete_hrimport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hremployee',
            name='blood_type',
            field=models.CharField(blank=True, max_length=10, verbose_name='Kan Grubu'),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='Departman'),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='import_confidence',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Okuma Güven Skoru (%)'),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='role',
            field=models.CharField(blank=True, max_length=200, verbose_name='Rol / Unvan'),
        ),
        migrations.AddField(
            model_name='hremployee',
            name='work_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='Çalışma Modeli'),
        ),
    ]
